### ISSUE TITLE
Replace argparse with docopt for describing CLI options and help

### ISSUE THREAD

**Issue by gtseres** [gautamkrishnar/socli#100]
There's a great tool called [docopt](http://docopt.org/) that simplifies the whole argument parsing and help displaying process. What one has to do is to add a POSIX compliant docstring to the file they need the help to be displayed in, and use docopt to parse it. docopt will then automatically generate all the CLI argument parsing and help displaying.

**Comment by gautamkrishnar** [comment]
@aaxu what do you think about this. Since @aaxu implemented the new parser using argparse i need his word on this, let's wait for his reply @gtseres. We also have some pending PRs that need to be merged. Lets hold this back untill the next version.
