### ISSUE TITLE
Code Maintenance

### ISSUE THREAD

**Issue by sk364** [gautamkrishnar/socli#109]
The current code is written in a single file (1,280 lines currently), which is soon going to unmanageable and unsanitary. I think it should be modular in nature, separated out into modules for their specific purpose.

For example:
* Separating printing to console methods in `helpers.py` (or, printer.py).
* Separation of `interactive` mode feature into `interactive.py`.
* Separation of `users` info feature into `users.py`.
* Separation of most of the global variables in `constants.py` (or, config.py)
* Moreover, keeping `socli.py` as for the main entry point purpose parsing the arguments and calling the necessary methods from different modules.

This will provide a cleaner approach to the developers to read, understand and debug code in the long run.

Also, the code doesn't follow any Python coding standards which is really disturbing. No offence :P.

**Comment by mohamedotnet** [comment]
I can participate in that.

**Comment by gautamkrishnar** [comment]
yes @sk364 I was thinking about it... I am busy with my job and i am not getting time to merge all these pending pull requests... We can think about this after merging all the pending ones...

**Comment by johnashu** [comment]
I am interested in this. :)

**Comment by sk364** [comment]
@johnashu Let's discuss your approach to this.

**Comment by gautamkrishnar** [comment]
Reserved for RGSOC(https://railsgirlssummerofcode.org). Closing this now.
