### ISSUE TITLE
"socli -u" crashes if a user hasn't asked questions or if they haven't answered any

### ISSUE THREAD

**Issue by simon3270** [gautamkrishnar/socli#112]
I've answered a couple of questions but not asked any, so socli -u crashes with:

$ socli -u

 User: simon3270

        Reputations: 151

        Badges:
                   Gold: 0
                 Silver: 1
                 Bronze: 3
                  Total: 4

        Stats:
Traceback (most recent call last):
  File "/usr/local/bin/socli", line 9, in <module>
    load_entry_point('socli==3.6', 'console_scripts', 'socli')()
  File "/usr/local/lib/python2.7/dist-packages/socli/socli.py", line 1063, in main
    userpage(user)
  File "/usr/local/lib/python2.7/dist-packages/socli/socli.py", line 706, in userpage
    except urllib.error.URLError:
AttributeError: 'module' object has no attribute 'error'

The fix is to check that the number of answers is non-zero before dividing by it.

I've just checked the latest code, and there is already a check on the top_answer_tags and top_question_tags lists having any entries before indexing into them.

I'll issue a Pull request soon

**Comment by mohamedotnet** [comment]
I pulled a request #110 , waiting for it to be merged.

**Comment by simon3270** [comment]
I think request 110 is already done (pretty sure it's already in my fork).

My fix was to the:
    rate = accepted / float(total_questions) * 100
line just above yours - that does a divide-by-zero if no questions have been asked.

**Comment by gautamkrishnar** [comment]
This is now fixed
