### ISSUE TITLE
AttributeError: 'module' object has no attribute error

### ISSUE THREAD

**Issue by Anjalizi** [gautamkrishnar/socli#117]
![capture](https://user-images.githubusercontent.com/26696144/36165472-ad2c26fe-1115-11e8-96a5-a8b8dca5cc35.PNG)
I'm receiving this error when I wrote the command 
`socli -u`

**Comment by gautamkrishnar** [comment]
Thanks @anjalizi for reporting the issue. This one is already fixed ans the fix is available on the development branch. It will be available on the next realase.
