### ISSUE TITLE
Mac: store socli in macports

### ISSUE THREAD

**Issue by AlexAkhremenko** [gautamkrishnar/socli#12]
Can anybody implement it?

Refer: https://www.macports.org/

**Comment by gautamkrishnar** [comment]
@AlexAkhremenko  I am not a mac user. Lets hope that someone can implement it.

**Comment by gautamkrishnar** [comment]
@deanWombourne can you implement this one? What is your opinion on this?

**Comment by gautamkrishnar** [comment]
@AlexAkhremenko i think someone is already working on it see:
https://www.freshports.org/misc/py-socli/

**Comment by donnell794** [comment]
I am a Mac user and am willing to implement, just not to sure how. I'll look into it if you all would like. Any guidance @AlexAkhremenko ?

**Comment by gautamkrishnar** [comment]
@AlexAkhremenko u can use the guide: https://guide.macports.org/#development

**Comment by MatejMecka** [comment]
why not homebrew?
or is there one already

**Comment by gautamkrishnar** [comment]
No, it's not available in homebrew yet. If you are inetrested pls create one...
