### ISSUE TITLE
Improvising the --user

### ISSUE THREAD

**Issue by elath03** [gautamkrishnar/socli#121]
When we run `socli -u` , id is asked and after entering the id the information of user is displayed and the command is terminated. We have to again run `socli -d`.
Instead after running `socli -u`, id we can add 3 options:
1. check another user (automatically deletes the current configurations and asks for new id which we 
want to access)
2. Delete ( to delete the current configuration)
3. Exit

**Comment by gautamkrishnar** [comment]
Good suggestion 👍 Just assigned you...
