### ISSUE TITLE
-bash: socli: command not found

### ISSUE THREAD

**Issue by kalyaniasthana** [gautamkrishnar/socli#126]
kalyaniasthanaMon Feb 26~ $ pip3 install socli
Requirement already satisfied: socli in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: colorama in /usr/local/lib/python3.6/site-packages (from socli)
Requirement already satisfied: urwid in /usr/local/lib/python3.6/site-packages (from socli)
Requirement already satisfied: BeautifulSoup4 in /usr/local/lib/python3.6/site-packages (from socli)
Requirement already satisfied: Py-stackExchange in /usr/local/lib/python3.6/site-packages (from socli)
Requirement already satisfied: requests in /usr/local/lib/python3.6/site-packages (from socli)
Requirement already satisfied: six>=1.8.0 in /usr/local/lib/python3.6/site-packages (from Py-stackExchange->socli)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests->socli)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests->socli)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests->socli)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests->socli)
kalyaniasthanaMon Feb 26~ $ socli
-bash: socli: command not found
kalyaniasthanaMon Feb 26~ $ socli for loop in python syntax
-bash: socli: command not found

###I am having some trouble with getting started with SOCLI on my mac. I was wondering if anyone could help?

**Comment by varshika03** [comment]
Have you tried changing your PATH? I think this should work for mac :  <br> Type export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin" in the terminal.<br> If that fixes it, you can permanently resolve it by altering ~/.bash_profile file.

**Comment by kallepallimounikasmitha** [comment]
Did you try : pip install socli ?

**Comment by kalyaniasthana** [comment]
Yes

**Comment by kallepallimounikasmitha** [comment]
I think it is because of the python version (maybe). I am using 2.7 version it works fine for me!

**Comment by gautamkrishnar** [comment]
Hi @kalyaniasthana please run
```
sudo pip install socli --upgrade
```

**Comment by kalyaniasthana** [comment]
not working
<img width="1279" alt="screen shot 2018-03-16 at 11 24 01" src="https://user-images.githubusercontent.com/7582857/37505781-95c946fe-290c-11e8-81d5-6196e66e5976.png">

**Comment by hiteshkumardasika** [comment]
@kalyaniasthana  i suspect it is the issue with python version..did you try to run the command with pip instead of pip3?

**Comment by kalyaniasthana** [comment]
Not a python version problem. I installed it again with pip3. It's working now.

**Comment by gautamkrishnar** [comment]
@kalyaniasthana really happy to know that it finally worked.. 👍

**Comment by gautamkrishnar** [comment]
@kallepallimounikasmitha @hiteshkumardasika thanks for helping her out.
