### ISSUE TITLE
Lazy-loaded feature

### ISSUE THREAD

**Issue by snehalgupta** [gautamkrishnar/socli#127]
The lazy loaded feature works simply like any other infinite loading / lazy loading website.  The more you scroll, the more we load. Say, for example, I was looking for list of questions with a specific tag. The tool could show the top 10 questions, then as soon as I reach the end of scroll, it loads ten more! And this goes on until I want it to stop. @riyasinha and I are planning to work on this feature.

**Comment by gautamkrishnar** [comment]
This should be implemented as an option on `-iq` so that users can press a button to get the next 10 questions.

**Comment by AshirGuptash** [comment]
For this, we could possibly have a right/left arrow key to navigate sets of 10 questions which could be tracked by a 'pages' counter possibly right-aligned where you ask the user to select 0-9. Is this still active?

**Comment by gautamkrishnar** [comment]
@AshirGuptash yep, please explain the way you are planning to implement this, if you are interested.

**Comment by gautamkrishnar** [comment]
@AshirGuptash as of now i dont think that this feature is required anymore. This was created when we didnt had a proper CUI implementation. Now it is almost good. Closing it.
