### ISSUE TITLE
socli -u if user don't ask question crash

### ISSUE THREAD

**Issue by LuckyPigeon** [gautamkrishnar/socli#130]
Recently I use stackoverflow.com's user list to test socli -u's fuction, then I find out that socli -u if the user don't ask and question then the program will failed.
The error message just like this
Traceback (most recent call last):
  File "/usr/local/bin/socli", line 11, in <module>
    load_entry_point('socli==3.6', 'console_scripts', 'socli')()
  File "/usr/local/lib/python2.7/dist-packages/socli/socli.py", line 1063, in main
    userpage(user)
  File "/usr/local/lib/python2.7/dist-packages/socli/socli.py", line 706, in userpage
    except urllib.error.URLError:
AttributeError: 'module' object has no attribute 'error'

**Comment by mohamedotnet** [comment]
It has been fixed in the development repository and it will be ported to the master repo.

**Comment by LuckyPigeon** [comment]
According to my test, I reinstall socli again in case I was wrong, but when I use socli -u with random guy who didn't ask question in stackoverflow, it crash again. And last time I check, it seems to be pyExchange module have some condition didn't exclude so that this socli -u got failed.

**Comment by gautamkrishnar** [comment]
@LuckyPigeon its now fixed please use the latest version.
