### ISSUE TITLE
Error on keyboard interrupt

### ISSUE THREAD

**Issue by Insiyaa** [gautamkrishnar/socli#135]
On using `socli -u`, on pressing Ctrl+C throws error instead of quitting. The same issue is with `socli -a`. We would like to fix this.:)
Team codeVamps
RGSoc 2018

**Comment by nupurgunwant** [comment]
``socli -u`` is working perfectly well. Can you elaborate what kind of error you are facing?

**Comment by Insiyaa** [comment]
When default user is not set and it prompts to enter stack user ID, it throws error on keyboard interrupt. I guess it should simply exit...

**Comment by nupurgunwant** [comment]
It throws an error because whatever is typed is taken as character. "^C" is however a keyboard interrupt. If you want to exit, you can simply press enter.

**Comment by Insiyaa** [comment]
Yes but it should allow exiting with ctrl+c as it is commonly used to kill tasks...
