### ISSUE TITLE
Accepted answers should be preferred over voted answers

### ISSUE THREAD

**Issue by immonika** [gautamkrishnar/socli#137]
Accepted answers should be given more preference than voted answers because the person who raised the queries the best judge to evaluate the answer and he has implemented the solution.

**Comment by Sando1** [comment]
hi, i'd like to work on this.

**Comment by gautamkrishnar** [comment]
@Sando1 as of now some of the merging process i going on in the project. Will let you know once you are ready to go. Thanks a lot for your interest in contributing.

**Comment by Sando1** [comment]
Sure

**Comment by akaashhazarika** [comment]
I would like to work on this. Is the merging complete

**Comment by jfariasf** [comment]
Is this issue still unfixed? I'd like to a look...

**Comment by andrefpoliveira** [comment]
Hey :) I would like to pick this one up. Is anyone working on this?

**Comment by gautamkrishnar** [comment]
Closing this one since we added highlighting the accepted answer.
