### ISSUE TITLE
Unable to view answer section when question has long length

### ISSUE THREAD

**Issue by jorden789** [gautamkrishnar/socli#145]
Using a VGA Monitor (untried on other resolutions), I am unable to view answer sections when accessing questions returned by following example command:

`socli -iq python while loop`

Possible to add in addition for collapse of question section when viewing individual pages or page up/down feature?

**Comment by hedythedev** [comment]
Is the issue still happening with the latest version of socli? If so can you please provide a screenshot and open a new issue with the latest info, thank you
