### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by beeva-miguelsarries** [gautamkrishnar/socli#15]
If I try "socli potatoe" (which I believe refers to https://stackoverflow.com/questions/2098127/google-appengine-object-with-id-com-google-appengine-api-datastore-keyproduc) I get "Encoding error: Use "chcp 65001" command before using socli...".

I'm on Ubuntu x64.

Could this be related with pr #13?

**Comment by gautamkrishnar** [comment]
@beeva-miguelsarries i dont think that it is related to it... lets check

**Comment by gautamkrishnar** [comment]
Fixed :smile:
