### ISSUE TITLE
No output from socli

### ISSUE THREAD

**Issue by l1n3n01z** [gautamkrishnar/socli#150]
I tried installing socli on OS X, Windows and WSL (bash on windows). I don't get any output at all, except on Windows where I get a line informing me of the current code page.

Windows and WSL are python 3, OS X is python 2.

I specifically tried the example in the help file. I also tried using the -s flag with a few words that gave results on stackoverflowin the browser. When I used a nonsensical word I got "no results" but when I probably should have got output I got nothing.

I'm sorry for the lack of details, but I don't have time to dig into this right now without help, and hoping it's something really obvious that I've missed.

**Comment by gautamkrishnar** [comment]
@l1n3n01z yes socli is not functioning well as of now. We are revamping it (#149).

**Comment by l1n3n01z** [comment]
@gautamkrishnar Regardless of current development, shouldn't there be a "pinned" version when using pip for installation that should work?

**Comment by gautamkrishnar** [comment]
Yes @l1n3n01z The previous version was working fine... I am not sure what happened its not working now. There are several bug reports on it... Currently i don't have time to look into it...

**Comment by l1n3n01z** [comment]
Stackoverflow has changed their output. I fixed some parsing. I suspect more parsing changes might be needed, but at least I get output now. I created a pull request, hopefully according to procedure. https://github.com/gautamkrishnar/socli/pull/151

**Comment by gautamkrishnar** [comment]
@l1n3n01z new version has been released can you please test it and let me know

**Comment by l1n3n01z** [comment]
Seems to work as expected on OSX. Windows as well. WSL seems to not work in interactive mode, but I do get output on a simple lookup.

**Comment by dheepakg** [comment]
As this is working, can we close this issue?

**Comment by gautamkrishnar** [comment]
Thanks 👍
