### ISSUE TITLE
install not working in python 3.7

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/socli#152]
python setup.py install gives the following error:

```
running install
running bdist_egg
running egg_info
writing socli.egg-info/PKG-INFO
writing dependency_links to socli.egg-info/dependency_links.txt
writing entry points to socli.egg-info/entry_points.txt
writing requirements to socli.egg-info/requires.txt
writing top-level names to socli.egg-info/top_level.txt
reading manifest file 'socli.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '*.json'
writing manifest file 'socli.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.14-x86_64/egg
running install_lib
running build_py
installing package data to build/bdist.macosx-10.14-x86_64/egg
running install_data
copying socli.egg-info/PKG-INFO -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying socli.egg-info/SOURCES.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying socli.egg-info/dependency_links.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying socli.egg-info/entry_points.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying socli.egg-info/requires.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying socli.egg-info/top_level.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
socli.__pycache__.search.cpython-37: module references __file__
socli.__pycache__.user.cpython-37: module references __file__
Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    long_description="\n\n"+longd
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 220, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 273, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 383, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 422, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```
Travis: https://travis-ci.org/gautamkrishnar/socli/builds/534361695
Ref: https://github.com/pypa/setuptools/issues/1257

**Comment by gautamkrishnar** [comment]
@benoit-pierre any idea why this is not working even if i have upgrade command in travis.yml

**Comment by rsharafkandi** [comment]
I did:
$ python --version
Python 3.7.3
$ python setup.py install
running install
running bdist_egg
running egg_info
writing socli.egg-info/PKG-INFO
writing dependency_links to socli.egg-info/dependency_links.txt
writing entry points to socli.egg-info/entry_points.txt
writing requirements to socli.egg-info/requires.txt
writing top-level names to socli.egg-info/top_level.txt
reading manifest file 'socli.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '*.json'
writing manifest file 'socli.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/socli
copying socli/__init__.py -> build/lib/socli
copying socli/__main__.py -> build/lib/socli
copying socli/auth.py -> build/lib/socli
copying socli/socli.py -> build/lib/socli
copying socli/user_agents.txt -> build/lib/socli
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/socli
copying build/lib/socli/__init__.py -> build/bdist.linux-x86_64/egg/socli
copying build/lib/socli/__main__.py -> build/bdist.linux-x86_64/egg/socli
copying build/lib/socli/auth.py -> build/bdist.linux-x86_64/egg/socli
copying build/lib/socli/socli.py -> build/bdist.linux-x86_64/egg/socli
copying build/lib/socli/user_agents.txt -> build/bdist.linux-x86_64/egg/socli
byte-compiling build/bdist.linux-x86_64/egg/socli/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/socli/__main__.py to __main__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/socli/auth.py to auth.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/socli/socli.py to socli.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying socli.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying socli.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying socli.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying socli.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying socli.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying socli.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
socli.__pycache__.socli.cpython-37: module references __file__
creating 'dist/socli-3.6-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing socli-3.6-py3.7.egg
creating /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/socli-3.6-py3.7.egg
Extracting socli-3.6-py3.7.egg to /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages
Adding socli 3.6 to easy-install.pth file
Installing socli script to /home/ramin/Projects/soclievirt2/bin

Installed /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/socli-3.6-py3.7.egg
Processing dependencies for socli==3.6
Searching for urwid
Reading https://pypi.org/simple/urwid/
Downloading https://files.pythonhosted.org/packages/c7/90/415728875c230fafd13d118512bde3184d810d7bf798a631abc05fac09d0/urwid-2.0.1.tar.gz#sha256=644d3e3900867161a2fc9287a9762753d66bd194754679adb26aede559bcccbc
Best match: urwid 2.0.1
Processing urwid-2.0.1.tar.gz
Writing /tmp/easy_install-o3441lsw/urwid-2.0.1/setup.cfg
Running urwid-2.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-o3441lsw/urwid-2.0.1/egg-dist-tmp-27z5k2m4
warning: no files found matching 'CHANGELOG'
source/str_util.c:25:20: fatal error: Python.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "/usr/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/easy_install-o3441lsw/urwid-2.0.1/setup.py", line 84, in <module>
    setup(**setup_d)
  File "/home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Couldn't build the extension module, trying without it...
warning: no files found matching 'CHANGELOG'
creating /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/urwid-2.0.1-py3.7.egg
Extracting urwid-2.0.1-py3.7.egg to /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages
Adding urwid 2.0.1 to easy-install.pth file

Installed /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/urwid-2.0.1-py3.7.egg
Searching for Py-stackExchange
Reading https://pypi.org/simple/Py-stackExchange/
Downloading https://files.pythonhosted.org/packages/62/1b/09d4099a54971599ceabc19846c242a1bccd5d66bede7235894412eb4e11/py-stackexchange-2.2.7.tar.gz#sha256=848bf85d98b95706750c61572fc2a2677cb8566e96b078bbe6261f0e2d8252b4
Best match: py-stackexchange 2.2.7
Processing py-stackexchange-2.2.7.tar.gz
Writing /tmp/easy_install-4govlxgb/py-stackexchange-2.2.7/setup.cfg
Running py-stackexchange-2.2.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-4govlxgb/py-stackexchange-2.2.7/egg-dist-tmp-k7cb5apf
/home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '2.2.007' to '2.2.7'
  normalized_version,
zip_safe flag not set; analyzing archive contents...
Moving py_stackexchange-2.2.7-py3.7.egg to /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages
Adding py-stackexchange 2.2.7 to easy-install.pth file

Installed /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/py_stackexchange-2.2.7-py3.7.egg
Searching for colorama
Reading https://pypi.org/simple/colorama/
Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl#sha256=f8ac84de7840f5b9c4e3347b3c1eaa50f7e49c2b07596221daec5edaabbd7c48
Best match: colorama 0.4.1
Processing colorama-0.4.1-py2.py3-none-any.whl
Installing colorama-0.4.1-py2.py3-none-any.whl to /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages
Adding colorama 0.4.1 to easy-install.pth file

Installed /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/colorama-0.4.1-py3.7.egg
Searching for requests
Reading https://pypi.org/simple/requests/
Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl#sha256=9cf5292fcd0f598c671cfc1e0d7d1a7f13bb8085e9a590f48c010551dc6c4b31
Best match: requests 2.22.0
Processing requests-2.22.0-py2.py3-none-any.whl
Installing requests-2.22.0-py2.py3-none-any.whl to /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages
writing requirements to /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/requests-2.22.0-py3.7.egg/EGG-INFO/requires.txt
Adding requests 2.22.0 to easy-install.pth file

Installed /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/requests-2.22.0-py3.7.egg
Searching for BeautifulSoup4
Reading https://pypi.org/simple/BeautifulSoup4/
Downloading https://files.pythonhosted.org/packages/1d/5d/3260694a59df0ec52f8b4883f5d23b130bc237602a1411fa670eae12351e/beautifulsoup4-4.7.1-py3-none-any.whl#sha256=034740f6cb549b4e932ae1ab975581e6103ac8f942200a0e9759065984391858
Best match: beautifulsoup4 4.7.1
Processing beautifulsoup4-4.7.1-py3-none-any.whl
Installing beautifulsoup4-4.7.1-py3-none-any.whl to /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages
writing requirements to /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/beautifulsoup4-4.7.1-py3.7.egg/EGG-INFO/requires.txt
Adding beautifulsoup4 4.7.1 to easy-install.pth file

Installed /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/beautifulsoup4-4.7.1-py3.7.egg
Searching for six>=1.8.0
Reading https://pypi.org/simple/six/
Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl#sha256=3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c
Best match: six 1.12.0
Processing six-1.12.0-py2.py3-none-any.whl
Installing six-1.12.0-py2.py3-none-any.whl to /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages
Adding six 1.12.0 to easy-install.pth file

Installed /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/six-1.12.0-py3.7.egg
Searching for urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
Reading https://pypi.org/simple/urllib3/
Downloading https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl#sha256=b246607a25ac80bedac05c6f282e3cdaf3afb65420fd024ac94435cabe6e18d1
Best match: urllib3 1.25.3
Processing urllib3-1.25.3-py2.py3-none-any.whl
Installing urllib3-1.25.3-py2.py3-none-any.whl to /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages
writing requirements to /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/urllib3-1.25.3-py3.7.egg/EGG-INFO/requires.txt
Adding urllib3 1.25.3 to easy-install.pth file

Installed /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/urllib3-1.25.3-py3.7.egg
Searching for idna<2.9,>=2.5
Reading https://pypi.org/simple/idna/
Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl#sha256=ea8b7f6188e6fa117537c3df7da9fc686d485087abf6ac197f9c46432f7e4a3c
Best match: idna 2.8
Processing idna-2.8-py2.py3-none-any.whl
Installing idna-2.8-py2.py3-none-any.whl to /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages
Adding idna 2.8 to easy-install.pth file

Installed /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/idna-2.8-py3.7.egg
Searching for chardet<3.1.0,>=3.0.2
Reading https://pypi.org/simple/chardet/
Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl#sha256=fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691
Best match: chardet 3.0.4
Processing chardet-3.0.4-py2.py3-none-any.whl
Installing chardet-3.0.4-py2.py3-none-any.whl to /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /home/ramin/Projects/soclievirt2/bin

Installed /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/chardet-3.0.4-py3.7.egg
Searching for certifi>=2017.4.17
Reading https://pypi.org/simple/certifi/
Downloading https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl#sha256=046832c04d4e752f37383b628bc601a7ea7211496b4638f6514d0e5b9acc4939
Best match: certifi 2019.6.16
Processing certifi-2019.6.16-py2.py3-none-any.whl
Installing certifi-2019.6.16-py2.py3-none-any.whl to /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages
Adding certifi 2019.6.16 to easy-install.pth file

Installed /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/certifi-2019.6.16-py3.7.egg
Searching for soupsieve>=1.2
Reading https://pypi.org/simple/soupsieve/
Downloading https://files.pythonhosted.org/packages/35/e3/25079e8911085ab76a6f2facae0771078260c930216ab0b0c44dc5c9bf31/soupsieve-1.9.2-py2.py3-none-any.whl#sha256=e4e9c053d59795e440163733a7fec6c5972210e1790c507e4c7b051d6c5259de
Best match: soupsieve 1.9.2
Processing soupsieve-1.9.2-py2.py3-none-any.whl
Installing soupsieve-1.9.2-py2.py3-none-any.whl to /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages
Adding soupsieve 1.9.2 to easy-install.pth file

Installed /home/ramin/Projects/soclievirt2/lib/python3.7/site-packages/soupsieve-1.9.2-py3.7.egg
Finished processing dependencies for socli==3.6

**Comment by Roymprog** [comment]
Is this still a bug?
I tried to reproduce this using a fresh Python 3.7.x virtual environment created using Anaconda on my Ubuntu 18.04 x86_64.

**Comment by donaldtn** [comment]
I couldn't reproduce this issue on a new Ubuntu 18.04 droplet.

**Comment by darrencl** [comment]
Agreed with the others, couldn't reproduce this on Ubuntu 18.04 with Python 3.7.3

More info:
```
(base) darren@darren-Latitude-7490:~/project/socli$ python setup.py install
running install
running bdist_egg
running egg_info
creating socli.egg-info
writing socli.egg-info/PKG-INFO
writing dependency_links to socli.egg-info/dependency_links.txt
writing entry points to socli.egg-info/entry_points.txt
writing requirements to socli.egg-info/requires.txt
writing top-level names to socli.egg-info/top_level.txt
writing manifest file 'socli.egg-info/SOURCES.txt'
reading manifest file 'socli.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '*.json'
writing manifest file 'socli.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/socli
copying socli/__init__.py -> build/lib/socli
copying socli/socli.py -> build/lib/socli
copying socli/auth.py -> build/lib/socli
copying socli/__main__.py -> build/lib/socli
copying socli/user_agents.txt -> build/lib/socli
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/socli
copying build/lib/socli/__init__.py -> build/bdist.linux-x86_64/egg/socli
copying build/lib/socli/socli.py -> build/bdist.linux-x86_64/egg/socli
copying build/lib/socli/user_agents.txt -> build/bdist.linux-x86_64/egg/socli
copying build/lib/socli/auth.py -> build/bdist.linux-x86_64/egg/socli
copying build/lib/socli/__main__.py -> build/bdist.linux-x86_64/egg/socli
byte-compiling build/bdist.linux-x86_64/egg/socli/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/socli/socli.py to socli.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/socli/auth.py to auth.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/socli/__main__.py to __main__.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying socli.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying socli.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying socli.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying socli.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying socli.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying socli.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
socli.__pycache__.socli.cpython-37: module references __file__
creating dist
creating 'dist/socli-3.6-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing socli-3.6-py3.7.egg
creating /home/darren/anaconda3/lib/python3.7/site-packages/socli-3.6-py3.7.egg
Extracting socli-3.6-py3.7.egg to /home/darren/anaconda3/lib/python3.7/site-packages
Adding socli 3.6 to easy-install.pth file
Installing socli script to /home/darren/anaconda3/bin

Installed /home/darren/anaconda3/lib/python3.7/site-packages/socli-3.6-py3.7.egg
Processing dependencies for socli==3.6
Searching for urwid==2.1.0
Best match: urwid 2.1.0
Adding urwid 2.1.0 to easy-install.pth file

Using /home/darren/anaconda3/lib/python3.7/site-packages
Searching for py-stackexchange==2.2.7
Best match: py-stackexchange 2.2.7
Adding py-stackexchange 2.2.7 to easy-install.pth file

Using /home/darren/anaconda3/lib/python3.7/site-packages
Searching for colorama==0.4.1
Best match: colorama 0.4.1
Adding colorama 0.4.1 to easy-install.pth file

Using /home/darren/anaconda3/lib/python3.7/site-packages
Searching for requests==2.22.0
Best match: requests 2.22.0
Adding requests 2.22.0 to easy-install.pth file

Using /home/darren/anaconda3/lib/python3.7/site-packages
Searching for beautifulsoup4==4.8.1
Best match: beautifulsoup4 4.8.1
Adding beautifulsoup4 4.8.1 to easy-install.pth file

Using /home/darren/anaconda3/lib/python3.7/site-packages
Searching for six==1.12.0
Best match: six 1.12.0
Adding six 1.12.0 to easy-install.pth file

Using /home/darren/anaconda3/lib/python3.7/site-packages
Searching for certifi==2019.11.28
Best match: certifi 2019.11.28
Adding certifi 2019.11.28 to easy-install.pth file

Using /home/darren/anaconda3/lib/python3.7/site-packages
Searching for idna==2.8
Best match: idna 2.8
Adding idna 2.8 to easy-install.pth file

Using /home/darren/anaconda3/lib/python3.7/site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /home/darren/anaconda3/bin

Using /home/darren/anaconda3/lib/python3.7/site-packages
Searching for urllib3==1.24.3
Best match: urllib3 1.24.3
Adding urllib3 1.24.3 to easy-install.pth file

Using /home/darren/anaconda3/lib/python3.7/site-packages
Searching for soupsieve==1.9.2
Best match: soupsieve 1.9.2
Adding soupsieve 1.9.2 to easy-install.pth file

Using /home/darren/anaconda3/lib/python3.7/site-packages
Finished processing dependencies for socli==3.6
```

**Comment by gautamkrishnar** [comment]
This issue is fixed now
