### ISSUE TITLE
Queries using Google Search sometimes returns questions from different subdomains

### ISSUE THREAD

**Issue by cll0ud** [gautamkrishnar/socli#157]
I tried searching for "foreach javascript" and I got an answer from pt.stackoverflow.com instead of the international site. I'm guessing that's unexpected behavior as pt.stackoverflow.com is a different stack exchange site with it's own user ids and stuff.

Using -iq returns both sites mixed in the options. With -s it works as expected and returns only questions from stackoverflow.com.

**Comment by anirudnits** [comment]
Hi, I am currently looking at this issue.

**Comment by gautamkrishnar** [comment]
@anirudnits thanks 👍

**Comment by gautamkrishnar** [comment]
@anirudnits Tip:  changing this https://github.com/gautamkrishnar/socli/blob/refactoring/socli/search.py#L24 to www will solve this issue: 
```
google_search_url = "https://www.google.com/search?q=site:stackoverflow.com+"  # Google search query URL
```
to

```
google_search_url = "https://www.google.com/search?q=site:www.stackoverflow.com+"  # Google search query URL
```

Please test it out and let me know. Open a pr if everything works fine.

**Comment by anirudnits** [comment]
Will do and Thanks

**Comment by anirudnits** [comment]
@gautamkrishnar I changed the google_search_url in search.py file as you said and now it seems to work just fine. Going to open a PR now.

**Comment by gautamkrishnar** [comment]
Fixed in #158. Thanks a lot for reporting @cll0ud

**Comment by cll0ud** [comment]
That was fast! Thank you guys :)

**Comment by gautamkrishnar** [comment]
A new release has been deployed with this fix
