### ISSUE TITLE
not working in python 2.7

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/socli#159]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2410%20Funded-%2300A156.svg" />](https://issuehunt.io/r/gautamkrishnar/socli/issues/159)

While running https://github.com/gautamkrishnar/socli/tree/refactoring
I am getting the following error: 
```bash
$ python -m socli for loop java
Traceback (most recent call last):
  File "/Users/gautam/miniconda3/envs/socli/1/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/gautam/miniconda3/envs/socli/1/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/gautam/PycharmProjects/socli/socli/__main__.py", line 1, in <module>
    from socli.socli import main
  File "socli/socli.py", line 25, in <module>
    import socli.tui as tui
ImportError: No module named tui
```

This is related to python's module import difference between two versions.
https://stackoverflow.com/questions/30249119/difference-in-package-importing-between-python-2-7-and-3-4

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $10.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($10.00)
### Submitted pull Requests
- [#162 Fix for issue #159](https://issuehunt.io/r/gautamkrishnar/socli/pull/162)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/gautamkrishnar/socli/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by anirudnits** [comment]
Looking into it!

**Comment by gautamkrishnar** [comment]
We must make sure that it works on both 2x an 3x

**Comment by anirudnits** [comment]
while recreating the error, I got this
**ModuleNotFoundError: No module named 'socli.tui'; 'socli' is not a package**
is there something that I am missing?

**Comment by anirudnits** [comment]
Sorry, I am able to create the same error in python2 but when the try the same thing in python3 I am getting the above error. Can you please verify if you are getting the same in python3?

**Comment by gautamkrishnar** [comment]
Working fine for me on python 3.7

**Comment by anirudnits** [comment]
I went through the files, changing 
`import socli.tui`
to
`import tui`
should make it right. 
From what I understand, the first import statement looks for to import _tui_(maybe a function, variable or class) from _socli.py_ file. The second import statement imports all the classes from _tui.py_ file in the same directory.I guess that's what we are looking to do, please correct me if I'm wrong.

**Comment by gautamkrishnar** [comment]
@agarwalnishtha dont use socli.tui. I need imports as python 3 standard. You can learn more about it here: https://stackoverflow.com/questions/12172791/changes-in-import-statement-python3

We must implement it using https://www.python.org/dev/peps/pep-0328/

**Comment by anirudnits** [comment]
By using `sys.path.append(".")` should do the trick for both the versions.

> When a module named spam is imported, the interpreter first searches for a built-in module with that name. If not found, it then searches for a file named spam.py in a list of directories given by the variable sys.path. sys.path is initialized from these locations:

    The directory containing the input script (or the current directory when no file is specified).
    PYTHONPATH (a list of directory names, with the same syntax as the shell variable PATH).
    The installation-dependent default.

from **https://chrisyeh96.github.io/2017/08/08/definitive-guide-python-imports.html#basics-of-the-python-import-and-syspath**

By adding the path of the current directory using _sys.path.append_, python will always search the current directory for the specified module.

**Comment by anirudnits** [comment]
Tested it and it works for both the version 2 and 3+. Submitting the PR for the same. Do review it and let me know if there is anything wrong. Thanks

**Comment by anirudnits** [comment]
Tested it and it works fine. Submitted the PR for the same. Let me know if there is anything wrong. Thanks!

**Comment by gautamkrishnar** [comment]
closing this one for now

**Comment by gautamkrishnar** [comment]
Hi @anirudnits thanks for the PR, Here's your reward.

**Comment by anirudnits** [comment]
@gautamkrishnar  thanks  :)
