### ISSUE TITLE
Feature: automatically copy code to clipboard

### ISSUE THREAD

**Issue by Decagon** [gautamkrishnar/socli#17]
Allow the user to select the code chunk (with the keyboard) and press a button to copy it to the clipboard, maybe using `xclip`. This way, the code can be pasted into the editor very easily.

**Comment by gautamkrishnar** [comment]
I think the default terminal has this feature. In Linux a user cam simply mark and select a piece of code displayed on the terminal. He can simply right click the terminal and copy the selected code. It is not required implement it using python...

**Comment by Decagon** [comment]
The added advantage is that the user could keep their hands on the keyboard, as using the mouse is not really what terminals are meant for.

**Comment by gautamkrishnar** [comment]
@Decagon  Okay, Thanks i will try to implement it :smile:

**Comment by gautamkrishnar** [comment]
I can;t implement feature without adding a new dependency (pyperclip). Lets keep using the native method to copy the text from the terminal. I think there is no API to read the user selected text from the terminal. So, now lets keep this one closed. 

If you know any native way of implementing this one (It must support all platforms) Please feel free to open a new pull request.
