### ISSUE TITLE
Rotating IP Addresses and Proxies / Fixing Inconsistent Google Search

### ISSUE THREAD

**Issue by timsmaluk** [gautamkrishnar/socli#170]
The biggest flaw in this program is that the Google searches are inconsistent. Rotating just the headers is pointless if there is no IP rotation. Now I am willing to buy some private proxies in order to fix the "inconsistent google search" issue, however, I'm not going to do it if this community is inactive.

**Comment by gautamkrishnar** [comment]
@timsmaluk this will not be required anymore since we made the UserAgent limited to some values.
