### ISSUE TITLE
Release 4.0

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/socli#177]
Release 4.0 Discussion

### Breaking changes
- Drop support for python 2 
- At least python 3.5+ is required due to dependency with Colorama library (Colorma doesn't work for python <3.5, see: https://travis-ci.org/github/gautamkrishnar/socli/jobs/695663869)

### Bugs 
- Question stats not working

CC: @hedythedev @timsmaluk

**Comment by gautamkrishnar** [comment]
Released https://pypi.org/project/socli/4.0/

**Comment by hedythedev** [comment]
We should update the [requirements section of the README](https://github.com/gautamkrishnar/socli#requirements) to `python 3.5 or higher`
