### ISSUE TITLE
Fix [duplicate] question display in interactive mode

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/socli#195]
As of now for the question: https://stackoverflow.com/questions/3476732/how-to-loop-backwards-in-python
The intreactive mode displays the following:
command:`socli for loop python`

<img width="1440" alt="Screenshot 2020-07-09 at 8 26 17 PM" src="https://user-images.githubusercontent.com/8397274/87056125-d2d3e480-c222-11ea-9aa3-755fb7128907.png">

### Changes required
1. We should remove the text by stripping out the corresponding div:
```

This question already has answers here:?
                        ?




Loop backwards using indices in Python? [/questions/869885/loop-backwards-using-indices-in-python]
?
                                (15 answers)?


Closed 3 years ago.
```
div:
<img width="759" alt="Screenshot 2020-07-09 at 8 31 57 PM" src="https://user-images.githubusercontent.com/8397274/87056726-aa001f00-c223-11ea-9309-11d5380aadfe.png">

2. We should parse the div and get the real question's URL. 
We can show it as a `visit duplicate question` option before the quit option:
<img width="953" alt="Screenshot 2020-07-09 at 8 36 10 PM" src="https://user-images.githubusercontent.com/8397274/87056974-f3506e80-c223-11ea-9cfe-01f9b16f5f78.png">

So the new options will be:
```
↑: previous answer,  ↓: next answer, o: open in browser, ←: back, d: visit duplicate question, q: quit
```

**Comment by hedythedev** [comment]
Not sure if `v` is a suitable option, because it can also mean 'visit website', how about d?

**Comment by hedythedev** [comment]
Also, I think we can find these kind of questions by the `[duplicate]` title

**Comment by gautamkrishnar** [comment]
@hedythedev yea, `d` would be better, updated the issue. I think yea we can also find the duplicate by its title. But since we are extracting URL from that div, it's better to rely on that div itself to find the duplicate.

**Comment by suvhotta** [comment]
@gautamkrishnar @hedythedev  After user presses the "d" key, should the duplicate question be re-routed to a browser tab or should it be displayed in the CLI ?

**Comment by gautamkrishnar** [comment]
Nope it should open in the socli itself

**Comment by suvhotta** [comment]
Ok Can I work on this one? Or is it taken?
