### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by mrbasel** [gautamkrishnar/socli#202]
When I use `socli for loop in python syntax` or any other keywords I get 'No results found...'

**Comment by hedythedev** [comment]
This might be because of the web scraping and HTML changes like #163 again 🤔

**Comment by hedythedev** [comment]
I have just looked at the Google search result source code and for me it the class isn't `g` anymore, it's `r`, so this won't work:
https://github.com/gautamkrishnar/socli/blob/1242758db1a2075f488a6fb58b1b18f193693bde/socli/search.py#L81

**Comment by gautamkrishnar** [comment]
Oh! strange, @hedythedev can yu please make the changes on the class name and trigger a release if you are free? I will do that if you are not.

**Comment by hedythedev** [comment]
Sorry @gautamkrishnar I'm busy right now and Im currently on mobile and had been looking at the source on mobile, so you might want to confirm the class name for you.

**Comment by gautamkrishnar** [comment]
Okay, @hedythedev I will have a look. thanks for the info.

**Comment by gautamkrishnar** [comment]
LOL this time it was not google, It was StackOverflow itself.

**Comment by suvhotta** [comment]
Hi @gautamkrishnar  this might be always the case when we are scraping, so if similarly some tag or anything changes then SoCLI might not perform as expected. So can't we move to an API based thing instead of scraping?  
https://api.stackexchange.com/docs

**Comment by gautamkrishnar** [comment]
@suvhotta Using API has some limitations.  Please check https://github.com/gautamkrishnar/socli/issues/178
