### ISSUE TITLE
query search algorithm

### ISSUE THREAD

**Issue by ankushduacodes** [gautamkrishnar/socli#203]
Hi, I was wondering how does query search chooses which question to show for a particular query
for example `socli for loop in python` shows a question that is mostly irrelevant to the question being asked

that's not even the most relevant or voted question when we search for same on the website

please help me understand whats going on?
![Screenshot 2020-09-02 at 1 09 33 PM](https://user-images.githubusercontent.com/61025943/91949145-aa95cd00-ed1d-11ea-8604-3e1159ccce57.png)

**Comment by gautamkrishnar** [comment]
@ankushduacodes by default it uses google search. it will take up the first result in google. If you want to use StackOverflow native search use `-s` or `--sosearch` argument. Ie: `socli -s for loop in python`

**Comment by ankushduacodes** [comment]
This doesn't seem to be true according to the project documentation and seem to be quite the opposite.
<img width="842" alt="Screenshot 2020-09-07 at 9 41 29 AM" src="https://user-images.githubusercontent.com/61025943/92347734-a0dde200-f0ee-11ea-80fb-57973c4e529a.png">
