### ISSUE TITLE
Toggle to go back to original question when in visiting duplicate url

### ISSUE THREAD

**Issue by ankushduacodes** [gautamkrishnar/socli#216]
There should be a toggle to go back to the original(means first visited url) question when we go to duplicate URL(means when we press d to go to the duplicate URL)

**Comment by abstanton** [comment]
Hi, could you assign me this issue? Had a look and am sure I can do it

**Comment by gautamkrishnar** [comment]
@abstanton thanks for your interest

**Comment by abstanton** [comment]
@gautamkrishnar Hi, I've submitted my pull request, looking forward to you having a look at it

**Comment by ankushduacodes** [comment]
@gautamkrishnar This should be a fairly easy enhancement to make. My suggestion is to add a label for the good first issue on this.
