### ISSUE TITLE
add --version flag

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/socli#220]
add `socli --version` and `socli -v` to print out the installed version to the console.

**Comment by NFuture** [comment]
I am a noob and would like to help you with the issue. I am a participating for the hacktoberfest and i know python so can I help you sir.

**Comment by gautamkrishnar** [comment]
Welcome to the community @NFuture

**Comment by NFuture** [comment]
> Welcome to the community @NFuture 

Thank you. Do I just have to add it to the parser.py ?!

**Comment by gautamkrishnar** [comment]
@NFuture you need to add it to the **parser.py** first, then you need to add the actual code executed to **socli.py**.

**Comment by NFuture** [comment]
Is the version mentioned anywhere in the code ?? I am can't find it. Should I declare a new constant which denotes the version.

**Comment by gautamkrishnar** [comment]
You can take the following as an example:
https://github.com/gautamkrishnar/socli/blob/983999fe7bf30baa9b7115dc34d8b3f9ffe01d35/socli/parser.py#L29

https://github.com/gautamkrishnar/socli/blob/983999fe7bf30baa9b7115dc34d8b3f9ffe01d35/socli/socli.py#L339-L342

SoCLI should immediately exit with 0 after displaying the version.

You can get version from version.py, please use the solution from: https://stackoverflow.com/a/24517154

**Comment by gautamkrishnar** [comment]
@NFuture thanks a lot for your interest. This is fixed on #221. Please feel free to work on other issues if you like..
