### ISSUE TITLE
Add sentry for error logging

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/socli#225]
Add sentry to **socli**:

Install the dependency:
```bash
pip install --upgrade sentry-sdk
```
Call it on the socli.py
```python
import sentry_sdk
sentry_sdk.init(
    "https://95c4106659044cbda2ea0fe499f4be7e@o323465.ingest.sentry.io/5445901",
    traces_sample_rate=0.5
)
```

Make sure that this code will run only when the user installed the package via pip, not during the development when someone runs `python -m socli`.

**Comment by pstreff** [comment]
Hello, I would like to work on this.

**Comment by gautamkrishnar** [comment]
@pstreff feel free to take it up

**Comment by pstreff** [comment]
> when someone installs the cli. Not while developing.

Do you mean that f someone installs the `requirements.txt`. Or are there any environment variables set to determine if we are in development mode?

**Comment by gautamkrishnar** [comment]
@pstreff that's the problem. I don't have a solution to that yet.

**Comment by gautamkrishnar** [comment]
@pstreff after digging a bit found a solution, just add the code below to the https://github.com/gautamkrishnar/socli/blob/bec571aca617e6eee2daed6eca4a908694dc8e8b/socli/__main__.py#L1-L4

```python
from socli.socli import main

if __name__ == '__main__':
    main(True)
```

And use the flag in https://github.com/gautamkrishnar/socli/blob/bec571aca617e6eee2daed6eca4a908694dc8e8b/socli/socli.py#L318-L322

Like:
```python
def main(is_dev=False):
    """
    The main logic for how options in a command is checked.
    """
    if is_dev:
        #Do stuff here
```

**Comment by pstreff** [comment]
@gautamkrishnar I found a different solution.
By creating `sentry.py` 
```
# Initialize Sentry
import sentry_sdk

from socli.socli import main

# Init Sentry here

main()
```
and then we can call this from `setup.py` `entry_points={"console_scripts": ['socli = socli.sentry:main']},`

Let me know what you think

**Comment by gautamkrishnar** [comment]
@pstreff Great!. your approach looks clean, lets do it like below:
```py
# Initialize Sentry
import sentry_sdk
# Init Sentry here

from socli.socli import main
main()
```

So that it will catch any import errors too.

**Comment by gautamkrishnar** [comment]
@hedythedev do you have anything else to add here?
