### ISSUE TITLE
Flag to output to std out

### ISSUE THREAD

**Issue by pspiagicw** [gautamkrishnar/socli#232]
# Flag to output directly to std out

## Features
A flag such as --raw-output could be implemented which just outputs the search result or the stackoverflow answer as machine parseable output.This enables it to be used in scripts where data manipulation tools like sed and awk could be used for the user's script

## Usablity

Usefule in scripts automating the workflow if implemented properly

**Comment by godspeed5** [comment]
I'll try doing this

**Comment by pspiagicw** [comment]
Is this available.I am interested in doing this if nobody wants to do it.

**Comment by gautamkrishnar** [comment]
closing this once since we have json output now. Raw output is not required anymore. This json output can be printed using appropriate tools like jq.
