### ISSUE TITLE
Add bash completion to socli

### ISSUE THREAD

**Issue by pspiagicw** [gautamkrishnar/socli#234]
Use https://github.com/kislyuk/argcomplete along with argparse to enable bash-completion.

**Comment by pspiagicw** [comment]
It would be great if the cli stores the n previous operations where n is a number chosen according to storage and memory.
In simple words it could have a history like bash_history

**Comment by gautamkrishnar** [comment]
We can use some libraries like https://github.com/kislyuk/argcomplete to provide bash shell completion.

**Comment by gautamkrishnar** [comment]
@pspiagicw updated the Issue.

**Comment by chetak123** [comment]
can i take this issue as part of DWOC

**Comment by gautamkrishnar** [comment]
@chetak123 yes you can make sure that you explain what you are planning to do here first.
