### ISSUE TITLE
Missing ManPage for Socli

### ISSUE THREAD

**Issue by pspiagicw** [gautamkrishnar/socli#235]
It would be great to have a manpage for socli.As this would enable fish(Shell) to scan them and provide help messages with a alternative help system

**Comment by pspiagicw** [comment]
If somebody does not want to do it.I could do it as it looks easy.

**Comment by gautamkrishnar** [comment]
@pspiagicw thanks a lot for reporting feel free to open a pull request 😄

**Comment by gautamkrishnar** [comment]
Fixed on #236
