### ISSUE TITLE
Vim Keybindings for Interactive Mode

### ISSUE THREAD

**Issue by pspiagicw** [gautamkrishnar/socli#237]
It would be good to have vim keybindings.This does not break the flow while working with vim or vim based applications.
I would like to work on it if  nobody else wants to.

**Comment by pspiagicw** [comment]
Sorry for submitting PR before you could reply to this one.I am really sorry

**Comment by gautamkrishnar** [comment]
@pspiagicw can you please explain what a vim keybinding is and its use case.

**Comment by pspiagicw** [comment]
Vim keybindings are keybindings used in the vim text editor.These are j for down k for up h for left(back) and l for right(forward).This in socli means that for going to the next question along with pressing down key one can press j key and for going to the previous question we could press k along with the up key.This would help a lot of users who are fluent in using vim as their text editor.I could record a demonstration if you want a demo of the mentioned PR.

**Comment by gautamkrishnar** [comment]
Closing this one please check #238
