### ISSUE TITLE
Emacs keybindings for socli

### ISSUE THREAD

**Issue by pspiagicw** [gautamkrishnar/socli#239]
It would be good to have both vim and emacs keybindings.I have already issued an PR for vim keybindings.
For just the sake of it we could add emacs keybindings.

**Comment by gautamkrishnar** [comment]
@pspiagicw can you please explain what an emacs keybinding is and its use case?

**Comment by pspiagicw** [comment]
Like the vim text editor emacs is another extensible editor used by a lot of Linux users.Emacs keybindings use Ctrl+n for down and Ctrl+p for up.So for going to the next answer we can use ctrl+n and ctrl+p for going to the previous answer.

**Comment by gautamkrishnar** [comment]
@pspiagicw really sorry to say this. I don't think that adding any text editor or application-specific shortcuts are required at this time. Thanks again for your suggestion.
