### ISSUE TITLE
Repeated name in contributors section in README

### ISSUE THREAD

**Issue by pspiagicw** [gautamkrishnar/socli#244]
I changed my username from prathampowar2001 to pspiagicw last month and thus there are repeated names in the contributors sectino. If you follow the link for prathampowar2001 it leads to an 404 error from github.I request you to remove prathampowar2001 from the list of contributors.As you have already added pspiagicw in the list.

**Comment by gautamkrishnar** [comment]
@all-contributors please remove @prathampowar2001 from the contributors list
