### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by tharunc** [gautamkrishnar/socli#249]
Hello there,
         I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time as a part of **DWOC**. Please assign me this issue. 
For reference, kindly check out: https://github.com/apps/welcome

THANK YOU

**Comment by gautamkrishnar** [comment]
@tharunc thanks, this will be a nice addition feel free to work on that
