### ISSUE TITLE
ADD CONTRIBUTING FILE AND ADD ALL GIT WORKFLOW AND MAKE IT LOOK NICE 

### ISSUE THREAD

**Issue by akrish4** [gautamkrishnar/socli#250]
Hi @gautamkrishnar @dstjacques @simon3270 @jm66 @kilbee @jericson 
I would like to contribute to this project , I found all the contributing gudelines are mentioned in the readme file itself , I would like to add a separate file named `contributing.md` file and add all the guidlines with the git commands to follow , KIndly assign me it

**Comment by gautamkrishnar** [comment]
LGTM just move the https://github.com/gautamkrishnar/socli#contributing section to CONTRIBUTING.md file. Thanks for your interest in contributing.

**Comment by akrish4** [comment]
> LGTM just move the https://github.com/gautamkrishnar/socli#contributing section to CONTRIBUTING.md file. Thanks for your interest in contributing.

Hi @gautamkrishnar 
I just need to move or shall i improve it little more ? Kindly let me know 
Kindly do add the `DWOC`and `Level-2` labels  to this issue @gautamkrishnar as this project is registered under dwoc

**Comment by gautamkrishnar** [comment]
I think nothing needs to be improved on that one, you can still add more stuff if you want. Yes, I will add those labels on the pr.

**Comment by akrish4** [comment]
> I think nothing needs to be improved on that one, you can still add more stuff if you want. Yes, I will add those labels on the pr.

Pls add in the issue also , they check both issue and pr 
@gautamkrishnar

**Comment by akrish4** [comment]
Hi @gautamkrishnar 
Pls add the `Level-2` label in this issue also , I have personally asked the core team , they said both issues and pr need to be labelled 
Pls add it , otherwise it may not be counted

**Comment by gautamkrishnar** [comment]
@akrish4 i talked with them too and they told me the exact opposite. Anyway i will add that label. 🙂

**Comment by akrish4** [comment]
Thank you
