### ISSUE TITLE
Create Issue Template

### ISSUE THREAD

**Issue by muthuannamalai12** [gautamkrishnar/socli#252]
Hai,
I would love to add an issue template for your repository. This template would have four issues namely bug, documentation, feature, proposal. It would look like the photo mentioned below.
![Template](https://user-images.githubusercontent.com/64524822/104024045-888aea80-51e8-11eb-91e9-d6699586545b.png)

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by gautamkrishnar** [comment]
LGTM

**Comment by muthuannamalai12** [comment]
I have created a pull request. Kindly review it
