### ISSUE TITLE
PR TEMPLATE 

### ISSUE THREAD

**Issue by muthuannamalai12** [gautamkrishnar/socli#259]
## 🚀 Feature
I can add a pr template , which will have few checklists and options like uploading screenshots and describing about the pr etc , which will give better understanding of pr for the maintainer
(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/gautamkrishnar/socli/blob/master/CONTRIBUTING.md)?
Yes
(Write your answer here.)

## Motivation
Self Motivation
(Please outline the motivation for the proposal.)

## Pitch
This is a great feature like issue template in this project , this will give a better idea about the pr and also make the work easy
(Please explain why this feature should be implemented and how it would be used.)

**Comment by gautamkrishnar** [comment]
@muthuannamalai12 right now I don't think that a pr template would is required, thanks a lot for opening an issue.
