### ISSUE TITLE
README enhancement 

### ISSUE THREAD

**Issue by anirudhsai20** [gautamkrishnar/socli#263]
## 📚 Documentation

(A clear and concise description of what the issue is.)
The README.md file can be enhenced by adding clear summary of what the project is about. It can also be enhanced by adding all the open source programs it has been listed in like DWOC and also adding citations if it all this project has been cited by any research paper.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/gautamkrishnar/socli/blob/master/CONTRIBUTING.md)?
Yes
(Write your answer here.)

**Comment by anirudhsai20** [comment]
Hi @gautamkrishnar. Can I please work on this issue under DWOC?

**Comment by gautamkrishnar** [comment]
no, the readme looks good for me right now.
