### ISSUE TITLE
Adding DWOC lables beside the issues.

### ISSUE THREAD

**Issue by anirudhsai20** [gautamkrishnar/socli#264]
## 📚 Documentation

(A clear and concise description of what the issue is.)
Labels of various open source programs that this project has been listed in like DWOC must be added beside each issue.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/gautamkrishnar/socli/blob/master/CONTRIBUTING.md)?
Yes.
(Write your answer here.)

**Comment by anirudhsai20** [comment]
Hi @gautamkrishnar . Please allow me to work on this issue under DWOC?

**Comment by gautamkrishnar** [comment]
nope i dont need this. Thanks for the interest.
