### ISSUE TITLE
Facing captchas even after adding my own Api Key 

### ISSUE THREAD

**Issue by iamtalhaasghar** [gautamkrishnar/socli#267]
## Actual Bug
The problem is that _**socli**_ still gives me the following captcha prompt.
`StackOverflow captcha check triggered. Please wait a few seconds before trying again. Try solving it manually: https://stackoverflow.com/nocaptcha?s=<some_random_number>`

and

**How do I make sure that `socli` is using my api key without any issues?**
Currently, it just says **api key added** when you enter it and there is no way to make sure if api key entered was correct or not. If correct, then whether `socli` is able to use it without any issue or not.

**Recommendation**
`socli` should do a test ping right after when user adds his/her api key and should tell the user if it`s working or not.

## Socli Version
 6.9

## Added api key to Socli using `socli --api` ?
Yes, I copied my api key from the red box below and pasted it to `socli --api` prompt.

![api-key](https://user-images.githubusercontent.com/46928648/118610699-914d8780-b7ab-11eb-88ce-a69fb9fec2ef.png)

## Stack App Settings

![oauth-settings](https://user-images.githubusercontent.com/46928648/118610702-927eb480-b7ab-11eb-9d36-5aced1791e1f.png)

## Added User Id to Socli using `socli -u` ?
 Yes, I did.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/gautamkrishnar/socli/blob/master/CONTRIBUTING.md)?
Yes, I have read the Contribution Guidelines.

**Comment by gautamkrishnar** [comment]
@iamtalhaasghar API Key is only used to fetch the user data when you use the `-u` argument. It is not actually used to fetch the answers.
