### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [gautamkrishnar/socli#268]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine socli/search.py and observe `extacts`, however expect to see `extracts`.
- Examine socli/search.py and observe `explictly`, however expect to see `explicitly`.
- Examine README.md and observe `automaticially`, however expect to see `automatically`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/socli/pull/new/bugfix_typos

Thanks.

**Comment by gautamkrishnar** [comment]
@timgates42 thanks for reproting.
