### ISSUE TITLE
no result found

### ISSUE THREAD

**Issue by raijadas** [gautamkrishnar/socli#277]
## 🐛 Bug Report

(After writing the example code in CLI. It does not give the output. The no result output comes out.)

C:\Users\Administrator>socli for array in python
[33mNo results found...[0m

C:\Users\Administrator>socli for array in python syntax
[33mNo results found...[0m

C:\Users\Administrator>socli for loop in python syntax
[33mNo results found...[0m

C:\Users\Administrator>socli java for loop
[33mNo results found...[0m

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/gautamkrishnar/socli/blob/master/CONTRIBUTING.md)?

()

**Comment by gautamkrishnar** [comment]
Google might've changed its HTML structure again. I Will take a look once I am free.

**Comment by raijadas** [comment]
> Google might've changed its HTML structure again. I Will take a look once I am free.

thanks for being active to the resolve issues.

**Comment by clouedoc** [comment]
I also get this issue when developing on a datacenter server.
I believe Google is just rate-limiting my IP. Too bad!

**Comment by FergusFettes** [comment]
I'm also having this issue, the app is unusable for me. (`socli -u` works but nothing else)

I understand this module isn't really maintained, just commenting to follow in case this is picked up at some point. Looks like a nice app!

If there were some more debugging tips that might also be helpful, in case someone in my situation can do something/ get more helpful info.
