### ISSUE TITLE
Use colorama instead of natively printing ASCII Color Codes

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/socli#28]
Use Colorama https://pypi.python.org/pypi/colorama to improve color support.

Currently the color is not supported by windows platform.

If you like to take up this issue, leave a comment below ⭐️  

### How to do
Just update the printing functions with corresponding colorama API call, Eg of a printing function:
```py
def print_header(str):
    print(format_str(str, bcolors.HEADER))
```
Replace `print(format_str(str, bcolors.HEADER))` with colorama API call.

**Comment by e-beach** [comment]
I want to make this happen, although I'm new to this project. Count me in!

**Comment by gautamkrishnar** [comment]
(Y)

**Comment by e-beach** [comment]
Sooo, the colors will not be quite as bright if we solely use colorama, as colorama does not support the high-intensity `\0333]9xm` (`x` in 0-7) color codes. But, I think it's acceptable. Alternatively, we could use different colors depending on the platform, but that would be complex and awkward for a minor difference.

Current:
![high-intensity-colors](https://cloud.githubusercontent.com/assets/13651458/21994553/e21912f2-dbe5-11e6-9fab-1ae7540421a0.png)

With Colorama:
![without-bright-colors](https://cloud.githubusercontent.com/assets/13651458/21994481/8a091788-dbe5-11e6-9656-422f3f950f8e.png)

**Comment by gautamkrishnar** [comment]
@e-beach Thanks. That won't be a problem. Its looking great... Please open a PR once it is complete 😄  👍
