### ISSUE TITLE
Bug: Queries don't show the right/true results 

### ISSUE THREAD

**Issue by adityatandon007** [gautamkrishnar/socli#30]
**Description of the bug**:

Running the socli command on terminal doesn't display the accurate or accurate results.

_People to notify_:
@gautamkrishnar 

**Steps to recreate:**
Try this in your terminal window

`socli for loop in python syntax` 

**Here is the screen shot of that command**
![screenshot from 2017-02-08 11-22-46](https://cloud.githubusercontent.com/assets/25108385/22725677/ef9a74cc-edf4-11e6-8c8a-d0cef15c48f5.png)

**Comment by adityatandon007** [comment]
@gautamkrishnar don't suggest solve this on your. I don't want to claim but I think it will be good for newbies. I have DM you on slack about this :smiley:

**Comment by adityatandon007** [comment]
@gautamkrishnar I have commented few newbies but since I am not the owner of this repo, I cannot add the labels to it. Would you add a label for this like *first-timers-only* or *low-hanging fruit*. About first timers they are doing a great job. I have read an article about the first timers on the net

**Comment by gautamkrishnar** [comment]
@adityatandon007 Added. :smile:  Thanks for reporting... :dancer:

**Comment by gautamkrishnar** [comment]
## Instructions to fix
Just remove the `tab=votes&` from [line 18](https://github.com/gautamkrishnar/socli/blob/master/socli/socli.py#L18) of socli.py

**Comment by Aksh77** [comment]
@gautamkrishnar I will try fixing this.

**Comment by gautamkrishnar** [comment]
@Aksh77 Thank you :smiley:
