### ISSUE TITLE
socli -u option fails with error for python2

### ISSUE THREAD

**Issue by e-beach** [gautamkrishnar/socli#33]
Error occurs because python2 does not support json.JSONDecodeError

```
$ socli -u
Traceback (most recent call last):
  File "/usr/local/bin/socli", line 9, in <module>
    load_entry_point('socli==3.2', 'console_scripts', 'socli')()
  File "/Library/Python/2.7/site-packages/socli/socli.py", line 573, in main
    except json.JSONDecodeError:
AttributeError: 'module' object has no attribute 'JSONDecodeError'
```

Solution: use this https://github.com/getsentry/raven-python/pull/208/commits/1f6b6520be42ff58052699703b38a4e51767ef67
 I'll open a PR in a second.

**Comment by gautamkrishnar** [comment]
Ih No... Travis CI Is showing tests success!. I will fix it.

**Comment by gautamkrishnar** [comment]
👍 Got it. its the problem with exceptions...
