### ISSUE TITLE
Use click command interface

### ISSUE THREAD

**Issue by e-beach** [gautamkrishnar/socli#37]
Using the [click ](http://click.pocoo.org/5/) interface would make the interface more modular. We could replace the command line parsing of inputs and delegation of commands with the click command's clean structure. Is this a change you feel is appropriate @gautamkrishnar?

**Comment by gautamkrishnar** [comment]
Yes exactly @e-beach 👍

**Comment by e-beach** [comment]
OK I'm going to implement this next to make other changes easier. If this had zero changes in functionality could you put it in the master branch?

**Comment by gautamkrishnar** [comment]
Yes sure... you can make a PR to the master...

**Comment by aaxu** [comment]
Is anyone working on this? I'm interested in taking over this issue.

**Comment by gautamkrishnar** [comment]
Thanks @aaxu Waiting for the PR! 🍺

**Comment by e-beach** [comment]
The problem with Click, I'm sorry to say, is that it is an <b>opinionated</b> framework that is not easily compatible with the current interface. It mainly exists to facilitate complex, interlocking CLIs for the Flask library.
 
I suggest using <b>argparse</b> instead, which would simplify the code while being more flexible and general. One root problem that made me consider changing the way arg processing works is that the -q and -i flags only work depending on a certain order, which we could fix using argparse.

**Comment by aaxu** [comment]
Do you mean its opinionated in that it assumes the program uses setuptools and virtualenv? I think click will work pretty well for this program although some slight changes may have to be made to the usage of the program. I think the only big changes to the user is that they will have to **pip install click** although it would be the same for argparse as well. There would also be some changes to the usage of the program. In particular, some changes will be made when making a query.

**Comment by e-beach** [comment]
@aaxu https://stackoverflow.com/questions/802050/what-is-opinionated-software
I mean that not all reasonable CLI syntaxes can be implemented with Click, and the current socli interface cannot be replicated with Click. It sounds like you have a good idea of what you want to do though.:smile: If you change the CLI, then there's no problem.

**Comment by aaxu** [comment]
Ahh. Well I've just been reading up on click. The big problem with it is that it doesn't allow for flags that are off by default, have a default argument if none is specified, and take an argument if it is. It also can't take in an unknown number of arguments if a flag is specified (it can only always take in an unknown number of arguments). This is a problem because it would either remove the query flags entirely or make it so that the user has to put the query in quotations if it is more than one word. I will come up with a list of possible changes in the next few days for each flag and post them so we can discuss which ones seem the most appropriate.

**Comment by gautamkrishnar** [comment]
Yes I also think that using the argparse is a better option. Lets close this issue. Thanks @e-beach for informing us. Thanks @aaxu for your interest.

**Comment by gautamkrishnar** [comment]
.
........

**Comment by aaxu** [comment]
Hmm okay I'll take a shot at argparse and see how it goes.
