### ISSUE TITLE
socli on windows with py2 and py3

### ISSUE THREAD

**Issue by daegontaven** [gautamkrishnar/socli#4]
i have both py2 and py3 on windows. I use py -2 and py -3 to open them respectively. But the socli command does not work. The command i used to install socli on cmd admin was:

    py -3 -m pip install socli

**Comment by gautamkrishnar** [comment]
Have you tried installing it using pip3 command. It is actually located inside your installation of python 3?

**Comment by gautamkrishnar** [comment]
@daegontaven what is the exact error you are receiving?

**Comment by gautamkrishnar** [comment]
@daegontaven it doesn't support python 2 i am implementing it on python 2 soon. Please use pip3 command to install socli

**Comment by daegontaven** [comment]
No, i know that. But on my machine the only way to access python 3 is using the command

    py -3 -m pip install socli

After doing this it gets installed. But it does not run when i enter socli into command prompt.

**Comment by gautamkrishnar** [comment]
@daegontaven  then you should try downloading the source and install it using setup.py. Download the latest source here: https://github.com/gautamkrishnar/socli/archive/1.4.zip

Extract the files. Open an administrative command prompt and use:
```
py3 setup.py install
```
