### ISSUE TITLE
Vim Bindings or Arrows for Interactive mode

### ISSUE THREAD

**Issue by krruzic** [gautamkrishnar/socli#41]
Would be cool to use this to select which item in the list you want. Then press enter to select or whatever.

**Comment by gautamkrishnar** [comment]
@e-beach what's your opinion on this?

**Comment by e-beach** [comment]
I'm not sure what this means, because currently there are 2 menus for interactive mode. 
The second menu (select answer) has the arrows in the manner described.
The first menu (select question) could be implemented with this, but would there be some sort of preview of the answers?

**Comment by gautamkrishnar** [comment]
I don't think that previewing answers while displaying questions would be a good option...
