### ISSUE TITLE
Silent quit when browsing unanswered quetions in interactive mode

### ISSUE THREAD

**Issue by arount** [gautamkrishnar/socli#48]
_I'm making an issue after the PR, the goal is to track bugs / PRs if this issue come back one day, hope it is appreciated._

When browsing in interactive mode an unanswered question `socli` just quit without any message.
I made a PR to fix the behavior which make thinking socli is bugged, which is not.

PR: https://github.com/gautamkrishnar/socli/pull/47

**Comment by gautamkrishnar** [comment]
👍 Thanks for reporting @arount 😄

**Comment by gautamkrishnar** [comment]
Closed via #47
