### ISSUE TITLE
BeautifulSoup findAll returning empty list of links

### ISSUE THREAD

**Issue by aaxu** [gautamkrishnar/socli#55]
I repeatedly ran the command "socli python for loop" and sometimes it would come up with a "No results found..." message. I noticed that if you run multiple queries within a certain interval, it would return this message with a high percentage, but this issue is not only limited to when you run multiple queries within a certain interval. It appears as though calling findAll() on the BeautifulSoup object in the socli function is returning an empty list. Tested this issue on both Python 2.7 and 3.6

**Comment by gautamkrishnar** [comment]
It may be because of the stackoverflow captcha  check. I will add some code in the next release to prevent this bug from happening again,

**Comment by aaxu** [comment]
This seems to also occur when I switched to the develop branch which uses google to retrieve the links and I don't think Google has captcha checks

**Comment by gautamkrishnar** [comment]
yes! that is a **work in progress** branch...

**Comment by aaxu** [comment]
I updated the google search so it shouldn't cause an error again when using it to search. If you spam searches to google, after a while, it'll cause a captcha check, but I'm not really sure how to go about resolving that through terminal. However, normal users shouldn't really encounter this problem.

**Comment by gautamkrishnar** [comment]
Fixed ✅
