### ISSUE TITLE
chcp 65001 Encoding Error

### ISSUE THREAD

**Issue by aaxu** [gautamkrishnar/socli#60]
I found that a particular page always produces this error on my Ubuntu which is using python 2.7.12. Try **socli -r 10 -q python for loop**. If this doesn't produce the error, then google probably changed the order of the results. You can try **socli -iq python for loop** and look for the result with the question name "How do I loop through a Python list by twos?"

Here is the link of the actual post on SO for reference:
* https://stackoverflow.com/questions/2990121/how-do-i-loop-through-a-python-list-by-twos

I have yet to see this encoding error occur in python 3 (I'm using python 3.5 and above on my other computer, although it could be because I'm running ArchLinux on that one and there may be some other differences other than the python version).

**Comment by gautamkrishnar** [comment]
Encoding error on ubuntu! I thought that it would only happen on windows...

**Comment by gautamkrishnar** [comment]
@aaxu are you using bash on ubuntu on windows 10?

**Comment by aaxu** [comment]
No, I have dual boot windows 10 and Ubuntu 16.04 on one of my computers. This bug happened on Ubuntu which was using terminal.

**Comment by gautamkrishnar** [comment]
You can simply use:
```
sudo pip uninstall socli
pip3 install socli
```
For installing socli for your python3. If it is throwing some error, just us `sudo easy_install pip`

**Comment by aaxu** [comment]
Okay I just tested it by installing the python3 version on my Ubuntu. The bug seems to be fixed, at least for the page that I linked before.

**Comment by aaxu** [comment]
Another example found for python 2.7 (which is conveniently linked inside the first example's question post):
`socli pythonic way to iterate over sequence`
link: https://stackoverflow.com/questions/3415072/pythonic-way-to-iterate-over-sequence-4-items-at-a-time

**Comment by mohamedotnet** [comment]
I got the same error on Ubuntu 17.04.
