### ISSUE TITLE
Implement Terminal Mode

### ISSUE THREAD

**Issue by sk364** [gautamkrishnar/socli#70]
Make SoCLI a REPL.
Command : socli --terminal
To Quit : Ctrl + c

Implementation : 
I will be using the Python Prompt Toolkit to develop this feature.
It will use the interactive mode feature to display questions and answers.

Any kind of query on this feature will be appreciated.

**Comment by thumpri** [comment]
I'm sorry but I didn't quite understand the new feature's implementation.
We already have the interactive mode to display questions and answers, what additions are you suggesting?

**Comment by sk364** [comment]
This feature can make SoCLI a REPL, as I mentioned. You can write questions directly in the shell-like interface, without the need to remember the commands.

**Comment by thumpri** [comment]
When we are in the interactive mode, we don't have to remember any commands.
For instance, socli -iq html error 404
Then all that is required is to press left arrow, top/down arrow or the index of the question we want the answer for.
What am I missing here?

**Comment by sk364** [comment]
But, then after your query, you get back to terminal, what if you wanted to ask another question!

**Comment by thumpri** [comment]
Oh okay.
I had never heard of REPL before. Sounds interesting.
Are you working on this feature?

**Comment by sk364** [comment]
https://en.wikipedia.org/wiki/Read–eval–print_loop

I did open a PR. I hadn't seen what happened to it.

**Comment by gautamkrishnar** [comment]
We have some issues related to this implementation since we added interactivity to all socli sub commands. So we are not planning to implement this as of now.
