### ISSUE TITLE
Bug in Specific Result Search ('--res/-r' argument)

### ISSUE THREAD

**Issue by sk364** [gautamkrishnar/socli#71]
There seems to be no error message when the user specifies a value less than zero for the argument '--res/-r'
Example query - 
`socli --res -10 -q <query_string>`

**Comment by sk364** [comment]
I can fix it. Shall I ?

**Comment by aaxu** [comment]
This is addressed in #69 when i implemented the new parser

**Comment by gautamkrishnar** [comment]
@sk364 Sorry. It was already implemented by @aaxu. Closing this one...
