### ISSUE TITLE
0:82 Execution Error when opening in browser on MacOS

### ISSUE THREAD

**Issue by donnell794** [gautamkrishnar/socli#80]
When opening a question using the 'o' command on MacOS, there is an execution error thrown saying "0:82 Execution Error: "{link}" doesn't understand the "open location" message 
<img width="1140" alt="screen shot 2017-07-02 at 10 02 52 pm" src="https://user-images.githubusercontent.com/11854190/27775676-4bb5e7fc-5f72-11e7-9f6c-8626a0ad287e.png">

In addition to this error, the link also does not open in my default browser Safari but rather in Firefox. With some research, I've found the issues are caused by the use of the web browser module with newer iterations of the MacOS system. The reason for the error is not clear but the default browser issue is caused by the way the module opens URLs. It just has a list of possible browsers and runs through said list stopping at the first one that works. This does not find the default browser.

I've actually taken then liberty of fixing the issue by using the system to open the link. @gautamkrishnar you should see a pull request

**Comment by donnell794** [comment]
anything i can help with? it seems like the big fish (homepage browsing) is already being taken care of

**Comment by gautamkrishnar** [comment]
Nothing as of now @donnell794... I will open a new issue if I need any help. Thanks 😄
