### ISSUE TITLE
Not able to use in windows

### ISSUE THREAD

**Issue by vikramnr** [gautamkrishnar/socli#83]
Is there any docs on how to use it on windows.

**Comment by gautamkrishnar** [comment]
@vikramnr Its Simple...
 

1. - Just download and install python from the linK: https://www.python.org/ftp/python/3.6.2/python-3.6.2-amd64.exe
2. - Don't forget to check "Add to path" while installing python... 
3. - After installing reboot your PC
4. - Open a command prompt as admin and run `pip install socli` command

**Comment by vikramnr** [comment]
@gautamkrishnar  I have installed socli but I'm not able use it.  I have tried few examples provided but its not working.  Could please advise on the usage.

**Comment by gautamkrishnar** [comment]
try 
```sh
easy_install socli
```

**Comment by vikramnr** [comment]
@gautamkrishnar  I'm able to use the tool and its great.  But I think usage can also contains screenshots for windows.  If you don't feel like kindly go ahead and close the issue.

**Comment by gautamkrishnar** [comment]
Really happy to know that it worked... We are focusing more on Linux and bash... Some of our dependencies don't support windows... Adding windows screenshots will make readme harder to read. If you need to use socli to its full potential please consider using it with bash on windows: https://msdn.microsoft.com/en-us/commandline/wsl/about
