### ISSUE TITLE
Release Version 3.7: Windows

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/socli#84]
The Recent update to the code made SoCLI incompatible with windows... We used urwind which will not work on windows terminal. We need to update the internal logic such that the SoCLI will offer minimum functionality in windows without using urwind.

The current code is at [Develop](https://github.com/gautamkrishnar/socli/tree/develop) branch...

#### Python knowledge required: Advanced

**Comment by johnashu** [comment]
Hi, 

I use windows 10 and both in Command Prompt and PowerShell work fine..

I was going to attempt to fix this problem but it appears fine..

Can you be more specific on the error or maybe its another module needing an update?

Anyhow.. Its  an amazing program .. love it!

**Comment by gautamkrishnar** [comment]
@johnashu I just need someone to test whether all the features are working fine on windows.  Happy to know that its working fine. We are going to release version 3.7 soon.
