### ISSUE TITLE
Posting on overflow and commenting.

### ISSUE THREAD

**Issue by prashantchahal26** [gautamkrishnar/socli#91]
I can pick this topic as soon as we are done with the authentication this feature can be implemented.
Thanks @gautamkrishnar

**Comment by gautamkrishnar** [comment]
You must wait till the authentication feature is implemented by @thumpri. You guys can also discuss the implementation in this issue.

**Comment by prashantchahal26** [comment]
Okay thats sounds good. We can work together on the authentication feature and work on these features later.

**Comment by gautamkrishnar** [comment]
@prashantchahal26 Lets close this for now due to some technical issues. @thumpri told me that you guys are working on implementing the stackoverflow homepage browsing feature. Thanks again for your intrest :smile:
