### ISSUE TITLE
SoCLI fails without X

### ISSUE THREAD

**Issue by maxschlosser** [gautamkrishnar/socli#92]
I was trying to use SoCLI without a running X Server in interactive and single query mode.  Both only show part of the result and then immediately close.

I used the following queries:
1. `socli -iq java for loop`
2. `socli -q java for loop`
3. `socli -q java` (this one apparently works fine)
4. `socli -iq java`

I am using python 3.6.2 and zsh 5.4.1.

It apparently works perfectly fine when running in xfce4-terminal.

EDIT: added version information

**Comment by gautamkrishnar** [comment]
Thanks for reporting...

**Comment by serendipity5497** [comment]
Hi, I am a beginner and I would like to contribute to it.

**Comment by gautamkrishnar** [comment]
Hi @serendipity5497. I am not sure whether it is fixable because It might be the issue of some  dependencies. Please verify whether you can  reproduce the bug in your pc.

**Comment by maxschlosser** [comment]
Using the sources (invoked with `python3 -i socli.py -iq hello world` on master/develop) i got the following stack trace (might lack some info, im unable to copy from my no X session).

Standard queries apparently work correctly this way.

```
In socli.py, in socli_interactive (line 635 on master): LOOP.run()
In urwid, in self.run(), self._run(), self.event_loop.run(), self._loop() (line 703): `ready, w, err = select.select(...)
OSError: [Errno 9] Bad file descriptor

During handling another exception occured:
In main, socli_interactive(query): sys.exit(0)
```   
On `develop` the stack trace starts at `dispres (line 425)`.

This might be an issue with urwid.

**Comment by gautamkrishnar** [comment]
thanks @maxschlosser for investigating the issue. As I mentioned earlier,  @serendipity5497 we can't-do anything on our side to fix the issue. Please try opening an issue at [urwind main repository](https://github.com/urwid/urwid) notifying them about the issue.
