### ISSUE TITLE
-r command works for negative inputs as well

### ISSUE THREAD

**Issue by thumpri** [gautamkrishnar/socli#95]
for e.g.-
socli$ python3 socli.py -r -5 -q http

It yields a result instead of showing, enter positive index only.

**Comment by gautamkrishnar** [comment]
cool... looks like a bug... :grinning:. you can fix it if you are interested...

**Comment by thumpri** [comment]
Yes! I have worked on it. Will be sending you a pull request shortly.

**Comment by gautamkrishnar** [comment]
@thumpri reported to me personally that this is working fine for development branch.
